name: eShopOnWeb Build and Test

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Zip Release folder
      run: |
        zip -r PublicApi_Release.zip  src/PublicApi/bin/Release/net8.0
        zip -r Web_Release.zip  src/Web/bin/Release/net8.0
        pwd
        ls
        
    - name: Upload Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "PublicApi_Release.zip;Web_Release.zip"
        tags: false
        draft: false
          
