name: eShopOnWeb Build and Test

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet publish ./eShopOnWeb.sln --configuration Release
    - name: Zip Release folder
      run: |
        zip -r PublicApi_Release.zip  src/PublicApi/bin/Release/8.0/publish
        zip -r Web_Release.zip  src/Web/bin/Release/8.0/publish
        
    - name: Upload PublicApi Release
      uses: actions/upload-artifact@v2
      with:
        name: PublicApi_Release
        path: ./PublicApi_Release.zip

    - name: Upload Web Release
      uses: actions/upload-artifact@v2
      with:
        name: Web_Release
        path: ./Web_Release.zip
